### ISSUE TITLE
Compile LLVM to Equivalent CIR

### ISSUE THREAD

**Issue by ktemkin** [reilabs/hieratika#24]
# Description

Use [Inkwell](https://github.com/TheDan64/inkwell) to ingest LLVM IR from a file on disk and translate it into the Cairo IR structure. This should use equivalent structures where they exist, and start by stubbing out to no-op polyfills where they do not.

At the end of this task, we should be able to ingest LLVM IR and translate it wholesale to `FlatLowered`, with little regard for semantic mismatches. In other words, where possible we want this phase to just use the _closest possible approximation_ for an operation.

**Comment by iamrecursion** [comment]
## Spec

- [ ] Work out whether we want to ingest text-mode LLVM IR or the bitcode.
- [ ] Ingest whichever is the case, loading it into Inkwell's definition.
- [ ] Determine which portions of LLVM's IR have analogues in `FlatLowered`.
- [ ] Compile each of these directly.
- [ ] Set up a basic mechanism to stub out to polyfill implementations by name, returning a descriptive "not implemented" error to start with.
- [ ] Set up a framework for semantic equivalence tests between Rust and our execution model, if possible. This may depend on being able to get some data in and some data out, but should work on byte patterns rather than higher-level data types.

**Comment by iamrecursion** [comment]
Just a brief update on this one: it has been somewhat stalled by the fact that #25 ended up involving us actually solving linkage! See there for more details. 

The process will look somewhat as follows:

- [ ] Ingest LLVM IR in from `.ll` files in the textual format.
- [ ] Do a linear scan through the file's top level and gather top-level constructs. This will allow us to gain type information for declarations and definitions, and resolve aliases and the like.
- [ ] Perform the compilation itself, generating `FLIR` (see #25 for more details, currently blocked on the existence of the FLIR structures). Consistency check calls against declarations, erroring descriptively if not.
- [ ] Perform a consistency check that ensures that all symbols have the correct linkage against the declarations and definitions.
- [ ] Output the `.flo` object file by serializing the `FLIR`.
