### ISSUE TITLE
Design the ALU

### ISSUE THREAD

**Issue by ktemkin** [reilabs/hieratika#27]
## Description

At the level of the CPU, arithmetic is not just the actual mathematical operations on numbers. The ALU has to encompass all of the operations and _state_ that is expected of an ALU, including endianness convention, uint-to-float conversions, int-to-float conversions, int-to-int conversions, uint-to-int conversions, int-to-uint conversions.

**Comment by iamrecursion** [comment]
Small correction: the _LLVM_ `add` opcode, not CairoVM. The latter wraps and has no concept of overflows as it operates on Felts.

**Comment by iamrecursion** [comment]
So it looks like we are in luck. I had missed it when skimming before, but it looks like the arithemtic opcodes do the sensible thing and abstract away the ALU state for things like this.

```rust
fn add(a: u64, b: u64) -> u64 {
  a + b
}
```

Has a body that contains the following instruction sequence:

```ll
  %0 = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %left, i64 %right), !dbg !17
  %_3.0 = extractvalue { i64, i1 } %0, 0, !dbg !17
  %_3.1 = extractvalue { i64, i1 } %0, 1, !dbg !17
  br i1 %_3.1, label %panic, label %bb1, !dbg !17
```

Of particular interest is:

- The fact that `@llvm.uadd.with.overflow.i64` returns a structure `{ i64, i1 }`. In other words, the result and the overflow as a boolean flag.
- That means that, while this instruction sequence extracts both directly (into `%_3.0` and `%_3.1` respectively), the extraction is still _explicit_ and hence we do not have to worry about reordering.

As discussed before, it is the caller's responsibility to panic, and we do indeed see this with the branching `br i1 %_3.1` on the extracted flag.

**Comment by iamrecursion** [comment]
You'll definitely need to check the [langref](https://llvm.org/docs/LangRef.html) for the full set of ALU operations to check that all of them do this, but it seems like we can probably get away without any kind of stateful ALU component. Instead, we can just provide all of the ALU's _operations_ as polyfill functions.

**Comment by iamrecursion** [comment]
I just want to make it clear that at this point we don't really _have_ an ALU. The task, now, is just about working out which operations fall under this umbrella that are not already accounted for by the existing tasks to implement polyfills. 

> ALU will have to target two concepts: instructions and intrinsics.

Not quite: instructions and _builtins_. Intrinsics are something slightly different. While we _will_ have intrinsics, they are not related to the ALU effort (or any of the polyfills in fact). 

> Maybe the behavior should just lead to panic?

We are mostly ignoring poisoning at the moment as Rust does not appear to use it in my experimentation. If we do have to deal with it we can come up with a design for it then, but I think we're good to leave it alone for now.

> In the above example of `add i32 %a, %b`, the polyfill would be named `__llvm_add_i32`

No, it would be `__llvm_add_i32_i32`. There should be a type specifier for every argument to the polyfill as it will help with selection.

> Our ALU implementation can then come with a test suite to verify that we follow the desired behavior

Our polyfills _must_ come with a test suite. There is little point to them otherwise. 

> We will need to have to handle the type conversion with pattern matching

Why do we need type conversion at all? Our implementations should ideally work on the correct bit width on input and output, rather than round-tripping through a different type. Is there a reason we can't do things that way?
